<!-- <head>
    <script src="https://kit.fontawesome.com/af7bdc5951.js" crossorigin="anonymous"></script>
    <title>My first page</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital@0;1&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital@0;1&family=Yeseva+One&display=swap"
        rel="stylesheet">
</head> -->

<footer class="footer">
    <div class="container">
        <div class="header__inner">
            <div class="footer__logo">VINYL RECORDS</div>
            <nav class="nav">
                <a class="nav__link" href="#">ПЛАСТИНКИ</a>
                <a class="nav__link" href="#">ПРОИГРЫВАТЕЛИ</a>
                <a class="nav__link" href="#">ДОСТАВКА И ОПЛАТА</a>
                <a class="nav__link" href="#">О НАС</a>
                <a class="nav__link" href="#">КОНТАКТЫ</a>
            </nav>
            <div class=".SMM_block">
                <a class="nav_link_second" href=""><i class="fa-brands fa-instagram-square"></i></a>
                <a class="nav_link_second" href="https://t.me/AlsushaApa"><i class="fa-brands fa-telegram"></i></a>
                <a class="nav_link_second"
                    href="https://wa.me/79003226611?text=%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82!%20%F0%9F%91%8B%20%D0%A5%D0%BE%D1%87%D1%83%20%D0%BA%D1%83%D0%BF%D0%B8%D1%82%D1%8C%20%D0%B2%D0%B8%D0%BD%D0%B8%D0%BB%D0%BE%D0%B2%D1%83%D1%8E%20%D0%BF%D0%BB%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%BA%D1%83"><i
                        class="fa-brands fa-whatsapp-square"></i></a>
            </div>
        </div>
    </div>
</footer>