<head>
    <script src="https://kit.fontawesome.com/af7bdc5951.js" crossorigin="anonymous"></script>
    <title>My first page</title>
    <meta http-equiv="Content-Type" content="text/html; charset=cp1251"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital@0;1&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital@0;1&family=Yeseva+One&display=swap"
        rel="stylesheet">
</head>
<body >
<header class="header">
    <div class="container">
        <div class="header__inner">
            <div class="header__logo">VINYL RECORDS</div>
            <nav class="nav">
                <a class="nav__link" href="#">ПЛАСТИНКИ</a>
                <a class="nav__link" href="#">ПРОИГРЫВАТЕЛИ</a>
                <a class="nav__link" href="#">ДОСТАВКА И ОПЛАТА</a>
                <a class="nav__link" href="#">О НАС</a>
                <a class="nav__link" href="#">КОНТАКТЫ</a>
            </nav>
            <a class="number" href="">+7 (928) 768-32-39</a>

            <a class="basket" href=""><i class="fa-solid fa-basket-shopping"></i></a>

        </div>
    </div>
</header>
</body>